# Generated by Django 5.2.17 on 2026-10-01 13:00

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=160)),
                ('slug', models.SlugField(max_length=200, unique=True)),
                ('artist', models.CharField(max_length=160)),
                ('description', models.TextField(max_length=5000)),
                ('starts_at', models.DateTimeField(db_index=True)),
                ('status', models.CharField(choices=[('BORRADOR', 'Borrador'), ('PUBLICADO', 'Publicado'), ('ARCHIVADO', 'Archivado')], db_index=True, default='BORRADOR', max_length=12)),
                ('image', models.ImageField(blank=True, upload_to='events/%Y/%m/')),
                ('artwork', models.CharField(choices=[('live', 'En vivo'), ('electronic', 'Electronica'), ('acoustic', 'Acustico')], default='live', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['starts_at', 'pk'],
            },
        ),
        migrations.CreateModel(
            name='Sector',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('capacity', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(0)])),
                ('active', models.BooleanField(default=True)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sectors', to='catalog.event')),
            ],
            options={
                'ordering': ['pk'],
            },
        ),
        migrations.CreateModel(
            name='Price',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('sector', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prices', to='catalog.sector')),
            ],
            options={
                'ordering': ['-pk'],
            },
        ),
        migrations.CreateModel(
            name='Venue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('address', models.CharField(max_length=220)),
                ('city', models.CharField(max_length=100)),
                ('active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['name', 'pk'],
                'constraints': [models.UniqueConstraint(fields=('name', 'city'), name='venue_name_city_unique')],
            },
        ),
        migrations.AddField(
            model_name='event',
            name='venue',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='events', to='catalog.venue'),
        ),
        migrations.AddConstraint(
            model_name='sector',
            constraint=models.UniqueConstraint(fields=('event', 'name'), name='sector_event_name_unique'),
        ),
        migrations.AddConstraint(
            model_name='sector',
            constraint=models.CheckConstraint(condition=models.Q(('capacity__gte', 0)), name='sector_capacity_nonnegative'),
        ),
        migrations.AddConstraint(
            model_name='price',
            constraint=models.CheckConstraint(condition=models.Q(('amount__gt', 0)), name='price_positive'),
        ),
        migrations.AddConstraint(
            model_name='event',
            constraint=models.CheckConstraint(condition=models.Q(('status__in', ['BORRADOR', 'PUBLICADO', 'ARCHIVADO'])), name='event_status_valid'),
        ),
    ]
